version: '3.9'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
